version: '3'
services:
  db:
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=db_user
      - POSTGRES_DB=rails_dev

  web:
    build: .
    image: uysimty/rails-sample
    command: bin/rails s -p 3000 -b '0.0.0.0'
    environment:
      - DATABASE_PASSWORD=password
      - DATABASE_USER=db_user
      - DATABASE_NAME=rails_dev
      - DATABASE_HOST=db
    ports:
      - "3000:3000"
    depends_on:
      - db
